// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbDivODTnaXMMmJJD0lLett54DeGQP3iE',
    appId: '1:319724109599:web:7ecbfedb1061062996ba2a',
    messagingSenderId: '319724109599',
    projectId: 'edunotify-13c14',
    authDomain: 'edunotify-13c14.firebaseapp.com',
    storageBucket: 'edunotify-13c14.firebasestorage.app',
    measurementId: 'G-FCPSM5FFZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAGG3gKK6NDGj7wW08gUgqgwT2XRuDA0w',
    appId: '1:319724109599:android:1f5b6d5bf1ca5c8e96ba2a',
    messagingSenderId: '319724109599',
    projectId: 'edunotify-13c14',
    storageBucket: 'edunotify-13c14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_0ngF3Uxqk3nn0Gr0_tgT7M-AN-jhvw',
    appId: '1:319724109599:ios:168d9550bb3ba6f796ba2a',
    messagingSenderId: '319724109599',
    projectId: 'edunotify-13c14',
    storageBucket: 'edunotify-13c14.firebasestorage.app',
    iosBundleId: 'com.example.edunotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_0ngF3Uxqk3nn0Gr0_tgT7M-AN-jhvw',
    appId: '1:319724109599:ios:168d9550bb3ba6f796ba2a',
    messagingSenderId: '319724109599',
    projectId: 'edunotify-13c14',
    storageBucket: 'edunotify-13c14.firebasestorage.app',
    iosBundleId: 'com.example.edunotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbDivODTnaXMMmJJD0lLett54DeGQP3iE',
    appId: '1:319724109599:web:d9f7eae51f13e87296ba2a',
    messagingSenderId: '319724109599',
    projectId: 'edunotify-13c14',
    authDomain: 'edunotify-13c14.firebaseapp.com',
    storageBucket: 'edunotify-13c14.firebasestorage.app',
    measurementId: 'G-MCFGE6YXFH',
  );
}
